remote: true
hybrid: true
onsite: true

experience_level:
  internship: false
  entry: true
  associate: true
  mid-senior-level: true
  director: false
  executive: false

job_types:
  full-time: true
  contract: false
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all_time: false
  month: false
  week: false
  24_hours: true

positions:
  - Software engineer

locations:
  - Germany

apply_once_at_company: true

distance: 100

company_blacklist:
  - wayfair
  - Crossover

title_blacklist:
  - word1
  - word2

location_blacklist:
  - Brazil

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 30

llm_model_type: openai
llm_model: 'gpt-4o-mini'
# llm_api_url: https://api.pawan.krd/cosmosrp/v1'
