remote: true

experienceLevel:
 internship: false
 entry: true
 associate: true
 mid-senior level: true
 director: false
 executive: false

jobTypes:
 full-time: true
 contract: true
 part-time: false
 temporary: false
 internship: false
 other: false
 volunteer: false

date:
 all time: true
 month: true
 week: true
 24 hours: true

positions:
  - Software Developer
  - DevOps
  - Cloud Developer
  - AWS Developer

locations:
  - Toronto

distance: 100

companyBlacklist:
  - Numeris

titleBlacklist:
  - Sales