remote: [true/false]

experienceLevel:
 internship: [true/false]
 entry: [true/false]
 associate: [true/false]
 mid-senior level: [true/false]
 director: [true/false]
 executive: [true/false]

jobTypes:
 full-time: [true/false]
 contract: [true/false]
 part-time: [true/false]
 temporary: [true/false]
 internship: [true/false]
 other: [true/false]
 volunteer: [true/false]

date:
 all time: [true/false]
 month: [true/false]
 week: [true/false]
 24 hours: [true/false]

positions:
  - position1
  - position2

locations:
  - Country1
  - Country2

distance: 100

companyBlacklist:
  - Company1
  - Company2

titleBlacklist:
  - word1
  - word2

llm_model_type: [openai / ollama]
llm_model: ['gpt-4o' / 'mistral:v0.3']
llm_api_url: [https://api.pawan.krd/cosmosrp/v1',  http://127.0.0.1:11434/]